name: json_placeholder_api
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  http: ^1.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  test: ^1.16.4
